### ISSUE TITLE
Use the DELVE GUI as a target IDE

### ISSUE THREAD

**Issue by ghost** [laher/regopher#5]
https://github.com/aarzilli/gdlv

I was thinking about all the work with VSCODE  and JS to get new things working.
And VSCODE with golang debugging does work surprisingly well. And VSCODE has so many other plugins related to golang and everything else.

But wanted to raise the idea of using a pure golang IDE.
Its mostly because it allows fast cycles on making new functionality because its golang ( and turtles ) all the way down and eases regression testing etc etc and a long list of the things that make using golang everywhere useful.

Imagine having a high quality refactoring and debugging tool for golang.
It would make it very easy to add a ton of other high quality tools.

Pros:
1. WIth WASM TinyGO humming along this would allow a IDE running in a web browser too for golang.
Sot of interesting since https://github.com/dave/jsgo is a Compiler as a Service.  This would mean you could code from a WebIDE and get refactoring, debugging and compiling.  Its pretty neat and useful.

Contra reasons also exist:
1. Its ONLY for golang coding and so seems sort of wasteful when there is VSCODE out there. Especially since its easy to integrate the refactoring too since the rename tool is already done and needs similar integration point.
2. NIH syndrome :)

**Comment by laher** [comment]
Hi. 

Sorry, you're suggesting to build an IDE with Go/WASM? Sounds like fun, go for it.

Closing because it's way outside the scope of regopher. Good luck with your idea :)
